# Generated by Django 4.2.2 on 2023-06-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_article_slug_blog_max_home_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='github_url',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='linkedin_url',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
